### PR TITLE
Support unknown tag selectors

### PR DESCRIPTION
**Pull request by htmlparser**

### CODE REVIEW

**Comment by ImportTaste** [comment]
@htmlparser Do you have any plans to integrate some of the many ignored push requests on pup's repo?

https://github.com/ericchiang/pup/pulls

**Comment by God-damnit-all** [comment]
@andremarianiello @htmlparser 
Do you have any plans to integrate some of the many ignored push requests on pup's repo?

https://github.com/ericchiang/pup/pulls

**Comment by htmlparser** [comment]
@ImportTaste 

not really, the code currently does what I need it to do

which ones do you need?

**Comment by God-damnit-all** [comment]
Well, you have a couple good ones here that didn't get merged into this fork (as far as I know):
https://github.com/ericchiang/pup/pull/109
https://github.com/ericchiang/pup/pull/111

And there's this useful tweak for Python 3 compatibility:
https://github.com/ericchiang/pup/pull/142

Lastly, these node selector features:
https://github.com/ericchiang/pup/pull/121
https://github.com/ericchiang/pup/pull/139

**Pull request merged**
